# Generated by Django 4.2 on 2026-03-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan_generator', '0002_doctor_patient_remove_careplan_patient_info_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
